### ISSUE TITLE
Technology name

### ISSUE THREAD

**Issue by dnrobin** [SiEPIC/SiEPICfab-EBeam-ZEP-PDK#1]
Might be interesting to change the technology name from 'Ebeam' to 'Ebeam_ZEP' to differentiate from the standard Ebeam PDK. I have done so manually by setting the <name></name> tag in the XML file so the new name shows up in KLayout.

**Comment by lukasc-ubc** [comment]
Where do you see “EBeam”?  We have it set to SiEPICfab_EBeam_ZEP

**Comment by dnrobin** [comment]
By default, when I installed the technology into '.klayout/tech/', KLayout recognized it as simply 'EBeam'. The name originated from the <name> tag in 'SiEPICfab_EBeam_ZEP.lyt'. Changing it from 'EBeam' to 'SiEPICfab_EBeam_ZEP' fixed the issue.

**Comment by lukasc-ubc** [comment]
@mustafacc this might be the problem we were seeing.

**Comment by lukasc-ubc** [comment]
Perhaps you are using the master branch? Try switching to experimental. 


Lukas Chrostowski
Professor, Electrical and Computer Engineering
University of British Columbia
Quantum Matter Institute
Member, College of the Royal Society of Canada
http://www.mina.ubc.ca/lukasc
http://siepic.ubc.ca
https://qmi.ubc.ca/about/directory/lukas-chrostowski

**Comment by dnrobin** [comment]
Yes, the issue is observed for the master branch. Switching for the experimental branch version has crashed my KLayout installation. I have not been able to recover even upon removing the technology... I will try and investigate more later.

**Comment by dnrobin** [comment]
Turns out my custom KLayout instance was causing the crash. I reinstalled from the latest OSX Catalina build and reinstalled SiEPIC_Tools from the package manager. Now the experimental branch version of ZEP works and indeed the technology name shows up correctly.
